# This is a basic workflow to help you get started with Actions

name: test env

# Controls when the workflow will run
on:
  workflow_dispatch:
permissions:
  id-token: write # This is required for requesting the JWT

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: |
          echo ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL
          echo ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN
      - name: Run a one-line script
        run: |
          echo VAR1=val1 >> $GITHUB_ENV
          echo VAR2= >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "<VAR1=$VAR1>"
          echo "<VAR2=$VAR2>"
          cat /proc/$$/environ | xargs -0 -n1
